# Generated by Django 4.2.4 on 2023-09-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('event_image', models.ImageField(upload_to='', verbose_name='Image')),
                ('creation_date', models.DateField(verbose_name='Date Published')),
                ('event_text', models.TextField(verbose_name='Event Text')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('button_url', models.URLField(verbose_name='Button URL')),
                ('button_text', models.CharField(max_length=100)),
            ],
        ),
    ]
