# Generated by Django 4.2.4 on 2023-09-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='tisk-now', max_length=40),
            preserve_default=False,
        ),
    ]
